In [1]:
import numpy as np
import pandas as pd
from PIL import Image

In [2]:
print("=== Beginner Level ===")

# Basic NumPy Arrays and Arithmetic
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Multiplication:", a * b)

# Basic Statistics
data = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))

=== Beginner Level ===
Addition: [5 7 9]
Multiplication: [ 4 10 18]
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [3]:
print("\n=== Intermediate Level ===")


try:
    df = pd.read_csv("data.csv")
    arr = df.to_numpy()
    print("Loaded CSV as NumPy array:\n", arr)

    # Element-wise operations
    print("Element-wise square:\n", arr ** 2)
    print("Sum of all elements:", np.sum(arr))
    print("Mean per column:", np.mean(arr, axis=0))

except FileNotFoundError:
    print("CSV file 'data.csv' not found. Skipping CSV part.")

# RGB to Grayscale on 3x3 sample
rgb_image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[125, 125, 0], [0, 125, 125], [125, 0, 125]],
    [[200, 200, 200], [50, 100, 150], [25, 75, 125]]
])
grayscale = (0.299 * rgb_image[:, :, 0] +
             0.587 * rgb_image[:, :, 1] +
             0.114 * rgb_image[:, :, 2])
print("Grayscale conversion (3x3 RGB):\n", grayscale.astype(int))



=== Intermediate Level ===
Loaded CSV as NumPy array:
 [[ 66 107 277]
 [ 55 141 244]
 [ 26 194 246]
 ...
 [ 14 194 272]
 [ 22 122 229]
 [ 55 156 251]]
Element-wise square:
 [[ 4356 11449 76729]
 [ 3025 19881 59536]
 [  676 37636 60516]
 ...
 [  196 37636 73984]
 [  484 14884 52441]
 [ 3025 24336 63001]]
Sum of all elements: 448154
Mean per column: [ 48.916 148.973 250.265]
Grayscale conversion (3x3 RGB):
 [[ 76 149  29]
 [110  87  51]
 [200  90  65]]


In [4]:
print("\n=== Advanced Level ===")

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
result = np.matmul(A, B)
print("Matrix Multiplication:\n", result)


=== Advanced Level ===
Matrix Multiplication:
 [[ 4  4]
 [10  8]]


In [5]:
# Broadcasting example
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
print("Broadcasting (add vector to rows):\n", matrix + vector)

Broadcasting (add vector to rows):
 [[11 22]
 [13 24]]


In [7]:
# Image to Grayscale and Blurring
try:
    img = Image.open("sample.jpg").resize((100, 100))  # Resize for speed
    img_np = np.array(img)

    if img_np.ndim == 3 and img_np.shape[2] == 3:
        gray = (0.299 * img_np[:, :, 0] +
                0.587 * img_np[:, :, 1] +
                0.114 * img_np[:, :, 2]).astype(np.uint8)

        gray_img = Image.fromarray(gray)
        gray_img.show()  # Display grayscale image

# Blurring
        def blur_image(image):
            kernel = np.ones((3, 3)) / 9
            padded = np.pad(image, ((1, 1), (1, 1)), mode='edge')
            blurred = np.zeros_like(image)

            for i in range(image.shape[0]):
                for j in range(image.shape[1]):
                    blurred[i, j] = np.sum(padded[i:i+3, j:j+3] * kernel)
            return blurred.astype(np.uint8)

        blurred = blur_image(gray)
        blurred_img = Image.fromarray(blurred)
        blurred_img.show()  # Display blurred image
    else:
        print("Image is not RGB format.")
except FileNotFoundError:
    print("Image file 'sample.jpg' not found. Skipping image processing.")
